version: "3.9"
services:
  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend-build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - frontend-build:/usr/share/nginx/html
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000"
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    container_name: mongo
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
  frontend-build:
